os: Visual Studio 2015
version: Build {build}

build_script:
  # dotnet info
  - cmd: dotnet --info
  # Run dotnet test 
  - cmd: cd src\DevZH.LibUI.Package
  - cmd: dotnet restore
  - cmd: dotnet copy-runtimes -p DevZH.LibUI.Internal  --enable-pack --configuration Release --output ../../artifacts

artifacts:
  - path: artifacts/*.nupkg
    name: libui build package

deploy:
- provider: NuGet
  server: https://www.myget.org/F/devzh/
  api_key:
    secure: rZ7DEc0Com5ZMUI/4asIgqUpfXn3TgoktxT7ZzyqXaBd57XymoLtpPLyLHswtfZK
  skip_symbols: true
  artifact: /.*\.nupkg/
