os: Visual Studio 2015
version: Build {build}

build_script:
  # dotnet info
  - cmd: dotnet --info
  # Run dotnet test 
  - cmd: cd src\DevZH.LibUI.Package
  - cmd: dotnet restore
  - cmd: dotnet copy-runtimes -p DevZH.LibUI.Internal
  - ps: dotnet pack -c Release -o ../../artifacts --version-suffix build-$(([DateTimeOffset]::Parse($env:APPVEYOR_REPO_COMMIT_TIMESTAMP)).ToUnixTimeSeconds())

artifacts:
  - path: artifacts/*.nupkg
    name: libui build package
